# Generated by Django 2.2.6 on 2019-11-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Адрес пиццерии'),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название пиццерии'),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_descriptions', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pizza_images/')),
                ('price', models.IntegerField(default=0)),
                ('pizzashop', models.ForeignKey(on_delete=models.SET(None), to='pizzashopapp.PizzaShop')),
            ],
        ),
    ]
